package com.twacker.view.views;

import com.twacker.model.TweetStreamer;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

public class SearchViewImpl extends CustomComponent implements SearchView, Button.ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button stopButton;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Button startButton;
	private TweetStreamer streamer = null;
	
	private static final long serialVersionUID = -6224565670170192401L;
	
	public static String ID = "search";
	
	
	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchViewImpl() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@Override
	public void enter(ViewChangeEvent event) {
		
		textField_1.focus();
		startButton.addClickListener(this);
		stopButton.addClickListener(this);
		
	}

	@Override
	public void buttonClick(ClickEvent event) {
//		UI.getCurrent().getNavigator().navigateTo(MainView.ID);
		
		if(event.getButton().equals(startButton)) {
			streamer = new TweetStreamer();
			streamer.startStreaming();
		}
		else if(event.getButton().equals(stopButton))
			streamer.stopStreaming();

		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// startButton
		startButton = new Button();
		startButton.setCaption("Start");
		startButton.setImmediate(true);
		startButton.setWidth("-1px");
		startButton.setHeight("-1px");
		mainLayout.addComponent(startButton, "top:300.0px;left:595.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("237px");
		textField_1.setHeight("-1px");
		mainLayout.addComponent(textField_1, "top:300.0px;left:343.0px;");
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("620px");
		textArea_1.setHeight("259px");
		mainLayout.addComponent(textArea_1, "top:381.0px;left:260.0px;");
		
		// stopButton
		stopButton = new Button();
		stopButton.setCaption("Stop");
		stopButton.setImmediate(false);
		stopButton.setWidth("-1px");
		stopButton.setHeight("-1px");
		mainLayout.addComponent(stopButton, "top:334.0px;left:595.0px;");
		
		return mainLayout;
	}

}
